packages:
  - 'packages/*'

catalog:
    '@types/node': ^22.7.3
    concurrently: ^9.0.1
    postcss: ^8.4.47
    eslint: 8.57.0
    prettier: ^3.3.3
    tailwindcss: ^4.0.0-alpha.24
    typescript: ^5.6.2
    vitest: ^2.1.1

